export const INCREASE_ROOM_COUNT = "INCREASE";
export const DECREASE_ROOM_COUNT = "DECREASE";
export const ADD_USER_DATA = "ADD_DATA";
export const ADD_BOOKING_DETAILS = "ADD_BOOKING_DETAILS";
export const INCREASE_TRAVELLER_COUNT = "INCREASE_TRAVELLER";
export const ADD_PRICING_DETAILS = "HOTEL_PRICE";
export const DECREASE_TRAVELLER_COUNT = "DECREASE_TRAVELLER";
